//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestTaskApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public class OrderView
    {
        public System.DateTime Date { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
        public string ProviderName { get; set; }
        public string OrderId { get; set; }
    }
}
